### ISSUE TITLE
Policy conflict ?

### ISSUE THREAD

**Issue by abhishekr700** [crdroidandroid/android_system_sepolicy#1]
I was compiling crDroid for perseus (Mi Mix3) and got these 

```
/home/abhishekr700/android/crdroid/out/host/linux-x86/bin/checkpolicy:  policy configuration loaded
/home/abhishekr700/android/crdroid/out/host/linux-x86/bin/checkpolicy:  writing CIL to /home/abhishekr700/android/crdroid/out/target/product/perseus/obj/ETC/plat_sepolicy.cil_intermediates/plat_sepolicy.cil
neverallow check failed at /home/abhishekr700/android/crdroid/out/target/product/perseus/obj/ETC/plat_sepolicy.cil_intermediates/plat_sepolicy.cil:10226 from system/sepolicy/public/property.te:314
  (neverallow base_typeattr_278 base_typeattr_279 (property_service (set)))
    <root>
    allow at /home/abhishekr700/android/crdroid/out/target/product/perseus/obj/ETC/plat_sepolicy.cil_intermediates/plat_sepolicy.cil:17980
      (allow system_server theme_prop (property_service (set)))

Failed to generate binary
Failed to build policydb
```

Appears to me as somehow the policy is allowing something at one place & denying at other. 
Please see to it

**Comment by 18796299507** [comment]
> I was compiling crDroid for perseus (Mi Mix3) and got these
> 
> ```
> /home/abhishekr700/android/crdroid/out/host/linux-x86/bin/checkpolicy:  policy configuration loaded
> /home/abhishekr700/android/crdroid/out/host/linux-x86/bin/checkpolicy:  writing CIL to /home/abhishekr700/android/crdroid/out/target/product/perseus/obj/ETC/plat_sepolicy.cil_intermediates/plat_sepolicy.cil
> neverallow check failed at /home/abhishekr700/android/crdroid/out/target/product/perseus/obj/ETC/plat_sepolicy.cil_intermediates/plat_sepolicy.cil:10226 from system/sepolicy/public/property.te:314
>   (neverallow base_typeattr_278 base_typeattr_279 (property_service (set)))
>     <root>
>     allow at /home/abhishekr700/android/crdroid/out/target/product/perseus/obj/ETC/plat_sepolicy.cil_intermediates/plat_sepolicy.cil:17980
>       (allow system_server theme_prop (property_service (set)))
> 
> Failed to generate binary
> Failed to build policydb
> ```
> 
> Appears to me as somehow the policy is allowing something at one place & denying at other.
> Please see to it

how to solve it

**Comment by Mikdadali** [comment]
Did you solve it?
